### ISSUE TITLE
404 Error - Pushover plugin page

### ISSUE THREAD

**Issue by vparmeland** [jkraemer/redmine_pushover#3]
Hi,

Error 404 on /settings/plugin/redmine_pushover

> Environment:
>   Redmine version                3.2.3.stable
>   Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
>   Rails version                  4.2.5.2
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Git                            2.1.4
>   Filesystem  
> Redmine plugins:
>   progressive_projects_list      3.0.1
>   redmine_checklists             3.1.5
>   redmine_dashboard              2.7.1
>   redmine_project_team           0.0.2
>   redmine_pushover               1.0.1

**Comment by jkraemer** [comment]
I have no idea why that might happen. I'm running the same version of Redmine and it works. Can you show the log file for that request? And just for good measure, check that `plugins/redmine_pushover/app/views/settings/_pushover.html.erb` is there.
