### ISSUE TITLE
installation for redmine behind firewall

### ISSUE THREAD

**Issue by adhiemsumitro** [jkraemer/redmine_pushover#4]
My pushover account is working, I can receive push notification using curl and from email. Somehow, after following the configuration guide, the notification not arrive at all. 

Is it possible to use the plugin for redmine installation behind corporate firewall ? We connect to internet use http proxy, and only outgoing http(s) traffic allowed.

**Comment by jkraemer** [comment]
Hi, the latest commit on master adds configuration options for setting up a proxy server. could you give that a try?

**Comment by adhiemsumitro** [comment]
Hi,
This is what I setup :
![image](https://user-images.githubusercontent.com/27270288/29269039-b7947d3a-8119-11e7-8c56-439b0c919179.png)



![image](https://user-images.githubusercontent.com/27270288/29269075-e399ca48-8119-11e7-8127-0b96afbf933c.png)

there are 3 variables above : lets name it A, B, C

I put below :
Pushover API Token = A
Pushover subscription URL = B
My Proxy for connecting to internet is http://10.9.99.142:8080/

The result : no update from intranet-redmine received on my pushover app.

Please suggest correction , and thankyou for your support
![image](https://user-images.githubusercontent.com/27270288/29269090-f5fe29a4-8119-11e7-926b-924222e290dd.png)

**Comment by jkraemer** [comment]
closing because old :)
